### ISSUE TITLE
Where were you with the goat? Goat's name?  Info on goat

### ISSUE THREAD

**Issue by alblubaugh** [epid8060fall2019/MiaCarmichael-Introduction#1]
Greetings,

I am Amanda, in your MADA course.  Nice to meet you!  For the Github Issues exercise, I thought I would ask you more about the goat picture you used to introduce yourself.

Is your infectious disease epidemiology in regards to goats?  Where were you when you had that picture taken?  Is it your goat?  Did it have a name?  It looks young! If you could add a few comments explaining this under your goat picture, I think that would be a great addition to the page to resolve this issue :)

To explain, I love goats!  I have two goats myself that you can see on my intro page.

Best,

Amanda

**Comment by mncarmic** [comment]
Hi Amanda! I went ahead and added some details about the goat to my page! He has nothing to due with my infectious disease epidemiology work, and I wish I knew his name, but we still had a good time together :). Also I checked out your intro page, nice goats!

Best, 
Mia
